name: app
description: "Adbventures Club"
publish_to: 'none'

#version: 3.0.0+43 #android
version: 3.8.0+0 #ios

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.1.3
  step_progress_indicator: ^1.0.2
  intl: ^0.20.2
  country_code_picker: ^3.1.0
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.27
  fl_country_code_picker: ^0.1.9+1
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4
  geolocator: ^14.0.1
  google_maps_flutter: ^2.10.0
  geocoding: ^4.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.14.2
  permission_handler: ^12.0.0+1
  easy_localization: ^3.0.7
  font_awesome_flutter: ^10.8.0
  flutter_slidable: ^4.0.0
  map_launcher: ^4.4.3
  device_info_plus: ^12.3.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.1.0
  cached_network_image: ^3.4.1
  pdf: ^3.11.1
  printing: ^5.13.4
  app_links: ^6.3.3
  go_router: ^17.1.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  open_file: ^3.5.10

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appIcon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/adaptive.png"
  web:
    generate: true
    image_path: "images/appIcon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/translations/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900  
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-Black.ttf
          weight: 900
